version: "3.9"

services:
  backend:
    build:
      context: ./sma-matching-backend
      dockerfile: Dockerfile
    container_name: sma-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development

  frontend:
    build:
      context: ./sma-cv-matching-app
      dockerfile: Dockerfile
    container_name: sma-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5000
